#!/usr/bin/env bash
# Installs the reverse proxy - Nginx

# Update package list
sudo apt update 

# Upgrade packages
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Set "Holberton School" as the content of the default index.html
echo "Holberton School" | sudo tee /var/www/html/index.html

# Output to terminal as well
echo "Holberton School"

# Start Nginx service
sudo service nginx start
